services:
  - type: web
    name: projeto-imagem-veiculo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    autoDeploy: true
    region: oregon